sudo: required
services:
  - docker

before_install:
  - docker build --tag voltterra/docker-frontend -f Dockerfile.dev --target base .

script:
  - docker run voltterra/docker-frontend npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-600376935962'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'
