# Dev stage is called base
FROM node:alpine as base

WORKDIR '/app'
RUN chown -R node:node /app

USER node

COPY --chown=node:node package.json .
RUN npm install

# this copy is not necessary; move it to a prod stage
COPY --chown=node:node . .

CMD ["npm", "run", "start"]

# 2nd stage is called differently 
FROM base as build